name    'puppetlabs-pe_upgrade'
version '0.0.1'
source 'https://github.com/adrienthebo/puppet-pe_upgrade'
author 'Adrien Thebo <adrien@puppetlabs.com>'
license 'Apache 2.0'
summary 'Automated upgrades of PE'
description 'Manage Puppet Enterprise upgrades'
project_page 'https://github.com/adrienthebo/puppet-pe_upgrade'

dependency 'nanliu/staging', '>= 0'
